https://github.com/mrdbourke/tensorflow-deep-learning#-00-tensorflow-fundamentals-exercises

### Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [4]:
import tensorflow as tf

vector = tf.constant([1, 2, 3])
scalar = tf.constant(9)
matrix = tf.constant([[4, 5, 6],
                      [7, 8, 9]])
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])

vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

2. Find the shape, rank and size of the tensors you created in 1.

In [13]:
print("vector: ", vector)
print("shape:", vector.shape)
print("rank:", vector.ndim)
print("size:", tf.size(vector).numpy())

vector:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
shape: (3,)
rank: 1
size: 3


In [14]:
print("scalar: ", scalar)
print("shape:", scalar.shape)
print("rank:", scalar.ndim)
print("size:", tf.size(scalar).numpy())

scalar:  tf.Tensor(9, shape=(), dtype=int32)
shape: ()
rank: 0
size: 1


In [15]:
print("matrix: ", matrix)
print("shape:", matrix.shape)
print("rank:", matrix.ndim)
print("size:", tf.size(matrix).numpy())

matrix:  tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)
shape: (2, 3)
rank: 2
size: 6


In [16]:
print("tensor: ", tensor)
print("shape:", tensor.shape)
print("rank:", tensor.ndim)
print("size:", tf.size(tensor).numpy())

tensor:  tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
shape: (2, 2, 3)
rank: 3
size: 12


3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [29]:
tensor_rand_1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_rand_2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_rand_1, tensor_rand_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5967368 , 0.42526996, 0.14066541, ..., 0.4934789 , 0.9583167 ,
         0.68113554],
        [0.9486661 , 0.00688016, 0.09535468, ..., 0.9236177 , 0.6029593 ,
         0.18719947],
        [0.2064538 , 0.87955725, 0.3543086 , ..., 0.95864224, 0.21377254,
         0.19040406],
        [0.9410809 , 0.30189717, 0.59614277, ..., 0.08395362, 0.20954251,
         0.7039716 ],
        [0.07343626, 0.111601  , 0.765452  , ..., 0.35781932, 0.779534  ,
         0.25864315]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.43572247, 0.12651718, 0.73191404, ..., 0.1750592 , 0.6297853 ,
         0.13053918],
        [0.16970265, 0.3278935 , 0.19082761, ..., 0.9778522 , 0.3860178 ,
         0.9128916 ],
        [0.6371367 , 0.4086547 , 0.97808707, ..., 0.38101804, 0.60915315,
         0.58260393],
        [0.987916  , 0.6207514 , 0.6114831 , ..., 0.01978707, 0.18355799,
         0.45989037],
        [0.57699

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [30]:
tf.transpose(tensor_rand_1) @ tensor_rand_2

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.5246232 , 1.1176146 , 1.3983858 , ..., 1.1544214 , 1.1038407 ,
        1.5341504 ],
       [1.1095073 , 0.69789475, 1.3623394 , ..., 0.46029598, 0.9579092 ,
        0.769523  ],
       [1.333814  , 1.2154744 , 0.8656764 , ..., 0.52543354, 1.1106358 ,
        0.9732057 ],
       ...,
       [1.271944  , 1.1137314 , 1.5420438 , ..., 1.4783717 , 1.5752057 ,
        1.6857066 ],
       [1.3128809 , 1.199935  , 1.1877513 , ..., 1.1085341 , 1.677095  ,
        1.2907821 ],
       [1.2945673 , 0.88251895, 1.1622564 , ..., 0.47688323, 0.96944195,
        0.8253253 ]], dtype=float32)>

In [31]:
tensor_rand_2 @ tf.transpose(tensor_rand_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[102.05907 ,  76.08124 ,  77.60083 ,  76.719376,  76.7279  ],
       [ 76.08124 , 101.514336,  76.15835 ,  73.0831  ,  75.30676 ],
       [ 77.60083 ,  76.15835 ,  98.36169 ,  75.064835,  74.119644],
       [ 76.719376,  73.0831  ,  75.064835,  98.62468 ,  74.42887 ],
       [ 76.7279  ,  75.30676 ,  74.119644,  74.42887 , 100.7686  ]],
      dtype=float32)>

In [32]:
tf.matmul(tf.transpose(tensor_rand_1), tensor_rand_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.5246232 , 1.1176146 , 1.3983858 , ..., 1.1544214 , 1.1038407 ,
        1.5341504 ],
       [1.1095073 , 0.69789475, 1.3623394 , ..., 0.46029598, 0.9579092 ,
        0.769523  ],
       [1.333814  , 1.2154744 , 0.8656764 , ..., 0.52543354, 1.1106358 ,
        0.9732057 ],
       ...,
       [1.271944  , 1.1137314 , 1.5420438 , ..., 1.4783717 , 1.5752057 ,
        1.6857066 ],
       [1.3128809 , 1.199935  , 1.1877513 , ..., 1.1085341 , 1.677095  ,
        1.2907821 ],
       [1.2945673 , 0.88251895, 1.1622564 , ..., 0.47688323, 0.96944195,
        0.8253253 ]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [33]:
tf.tensordot(tf.transpose(tensor_rand_1), tensor_rand_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.5246232 , 1.1176146 , 1.3983858 , ..., 1.1544214 , 1.1038407 ,
        1.5341504 ],
       [1.1095073 , 0.69789475, 1.3623394 , ..., 0.46029598, 0.9579092 ,
        0.769523  ],
       [1.333814  , 1.2154744 , 0.8656764 , ..., 0.52543354, 1.1106358 ,
        0.9732057 ],
       ...,
       [1.271944  , 1.1137314 , 1.5420438 , ..., 1.4783717 , 1.5752057 ,
        1.6857066 ],
       [1.3128809 , 1.199935  , 1.1877513 , ..., 1.1085341 , 1.677095  ,
        1.2907821 ],
       [1.2945673 , 0.88251895, 1.1622564 , ..., 0.47688323, 0.96944195,
        0.8253253 ]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [35]:
tensor_rand_3 = tf.random.uniform(shape=(224, 224, 3), minval = 0, maxval = 1)
tensor_rand_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.3531313 , 0.21400201, 0.5756936 ],
        [0.07822907, 0.79359865, 0.3441702 ],
        [0.12117505, 0.45338535, 0.39136398],
        ...,
        [0.9900049 , 0.24770021, 0.33663988],
        [0.06036508, 0.32867754, 0.8600358 ],
        [0.5060997 , 0.9958358 , 0.32864356]],

       [[0.6367974 , 0.3955717 , 0.98715174],
        [0.90089667, 0.1608665 , 0.46449924],
        [0.8478104 , 0.7796663 , 0.7521267 ],
        ...,
        [0.54353046, 0.11229503, 0.06318915],
        [0.46757805, 0.2656598 , 0.8862368 ],
        [0.7774956 , 0.7148416 , 0.7055743 ]],

       [[0.02440441, 0.1861918 , 0.36119723],
        [0.4363265 , 0.5433128 , 0.20688987],
        [0.3450122 , 0.07114422, 0.5162369 ],
        ...,
        [0.66895354, 0.5546433 , 0.96786904],
        [0.88854754, 0.36451817, 0.86660373],
        [0.03552258, 0.47873545, 0.02999747]],

       ...,

       [[0.29017794, 0.81343067, 0.27538574],
        [0.12

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [38]:
tf.reduce_max(tensor_rand_3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.999658  , 0.9989344 , 0.9932412 ],
       [0.99918973, 0.9842355 , 0.98715174],
       [0.9998958 , 0.99868226, 0.9982203 ],
       [0.992237  , 0.98083603, 0.99913824],
       [0.9978589 , 0.9846313 , 0.9943361 ],
       [0.99205995, 0.9968989 , 0.99893034],
       [0.9942714 , 0.99609804, 0.9954728 ],
       [0.998569  , 0.9968306 , 0.9988091 ],
       [0.994838  , 0.9949553 , 0.99065423],
       [0.9985503 , 0.9987799 , 0.9941853 ],
       [0.99596405, 0.9938942 , 0.9986577 ],
       [0.995469  , 0.9959761 , 0.9990877 ],
       [0.995358  , 0.9948703 , 0.9999423 ],
       [0.9996817 , 0.99773145, 0.99115944],
       [0.99271667, 0.9955847 , 0.9970503 ],
       [0.99656594, 0.99616754, 0.99068034],
       [0.99885225, 0.98643637, 0.9941226 ],
       [0.9956845 , 0.9999355 , 0.99889755],
       [0.993554  , 0.9981761 , 0.9991962 ],
       [0.9919239 , 0.98877454, 0.9975363 ],
       [0.9989966 , 0.997206  , 0.98826873],
     

In [39]:
tf.reduce_min(tensor_rand_3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.04856491e-03, 1.04045868e-03, 1.07812881e-03],
       [9.43183899e-04, 1.70814991e-03, 1.71041489e-03],
       [1.37186050e-03, 1.12164021e-03, 4.27782536e-03],
       [1.37805939e-03, 7.96186924e-03, 5.04493713e-03],
       [1.70874596e-03, 6.37555122e-03, 5.59091568e-03],
       [2.70307064e-03, 5.75160980e-03, 4.63950634e-03],
       [1.68740749e-03, 2.85089016e-03, 1.22090578e-02],
       [8.20946693e-03, 4.75299358e-03, 9.62972641e-04],
       [5.76281548e-03, 2.71189213e-03, 2.00116634e-03],
       [3.28254700e-03, 5.36441803e-05, 2.62498856e-03],
       [6.09743595e-03, 2.54869461e-04, 2.09379196e-03],
       [1.00706816e-02, 8.50260258e-03, 1.03790760e-02],
       [1.86649561e-02, 1.91450119e-03, 1.70519352e-02],
       [3.09419632e-02, 3.13949585e-03, 1.57475471e-04],
       [2.09450722e-04, 2.27721930e-02, 4.05955315e-03],
       [2.06532478e-02, 6.15119934e-04, 8.93592834e-04],
       [8.90505314e-03, 5.54418564e-03

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [47]:
tensor_rand_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_rand_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.82768214, 0.5212401 , 0.8716427 ],
         [0.88021314, 0.51318383, 0.9909687 ],
         [0.8484771 , 0.8269528 , 0.21449196],
         ...,
         [0.8424374 , 0.71176875, 0.8402033 ],
         [0.75210106, 0.9271145 , 0.60021305],
         [0.97558796, 0.00199902, 0.7249063 ]],

        [[0.6973494 , 0.0316335 , 0.31152713],
         [0.23100197, 0.22537482, 0.7777504 ],
         [0.04274011, 0.01298988, 0.44176853],
         ...,
         [0.99901736, 0.9518516 , 0.38128316],
         [0.9213563 , 0.66728556, 0.22576237],
         [0.29569876, 0.24794507, 0.5161234 ]],

        [[0.89017344, 0.8967651 , 0.9320333 ],
         [0.59418416, 0.90584207, 0.40102696],
         [0.26660955, 0.16296482, 0.45227122],
         ...,
         [0.6053393 , 0.44713712, 0.00996065],
         [0.32795608, 0.03758705, 0.6773033 ],
         [0.48873508, 0.07431853, 0.4005624 ]],

        ...,

        [[0.26771784, 0.62716043, 

In [49]:
tensor_rand_4 = tf.squeeze(tensor_rand_4)
tensor_rand_4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.82768214, 0.5212401 , 0.8716427 ],
        [0.88021314, 0.51318383, 0.9909687 ],
        [0.8484771 , 0.8269528 , 0.21449196],
        ...,
        [0.8424374 , 0.71176875, 0.8402033 ],
        [0.75210106, 0.9271145 , 0.60021305],
        [0.97558796, 0.00199902, 0.7249063 ]],

       [[0.6973494 , 0.0316335 , 0.31152713],
        [0.23100197, 0.22537482, 0.7777504 ],
        [0.04274011, 0.01298988, 0.44176853],
        ...,
        [0.99901736, 0.9518516 , 0.38128316],
        [0.9213563 , 0.66728556, 0.22576237],
        [0.29569876, 0.24794507, 0.5161234 ]],

       [[0.89017344, 0.8967651 , 0.9320333 ],
        [0.59418416, 0.90584207, 0.40102696],
        [0.26660955, 0.16296482, 0.45227122],
        ...,
        [0.6053393 , 0.44713712, 0.00996065],
        [0.32795608, 0.03758705, 0.6773033 ],
        [0.48873508, 0.07431853, 0.4005624 ]],

       ...,

       [[0.26771784, 0.62716043, 0.30486822],
        [0.56

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [53]:
tensor_2 = tf.constant([1, 2, 3, 4, 5, 4, 3, 2, 1, 0])
tensor_2

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [54]:
tf.argmax(tensor_2)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [55]:
tensor_2[tf.argmax(tensor_2)]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

10. One-hot encode the tensor you created in 9.

In [57]:
tf.one_hot(tensor_2, depth=6)

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)>

### Extra curriculum

Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
https://www.tensorflow.org/tutorials/quickstart/beginner
* Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

#### Set up tensorflow

In [59]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.8.0


#### Load a dataset

In [62]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [66]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [65]:
x_train.shape

(60000, 28, 28)

#### Build a machine learning model

In [67]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [68]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.09104898,  0.17646667, -0.38064474,  0.45338085, -0.539059  ,
         0.32469106, -1.0267426 , -0.42197323,  0.66038287,  0.36148193]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [70]:
tf.nn.softmax(predictions).numpy()

array([[0.08520653, 0.11134058, 0.06378273, 0.14686413, 0.05443831,
        0.12912981, 0.03342769, 0.06120041, 0.1806407 , 0.13396908]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.

In [71]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class) so the initial loss should be close to `-tf.math.log(1/10) =2.3

In [74]:
loss_fn(y_train[:1], predictions).numpy()

2.046937

Before you start training, configure and compile the model using Keras `Model.compile`. Set the `optimizer` class to `adam`, set the loss to the `loss_fn` function you defined earlier, and specify a metric to be evaluated for the model by setting the `metric` parameter to `accuracy`.

In [75]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

#### Train and evaluate your model
Use the 'Model.fit' method to adjust your model parameters and minimize the loss:

In [77]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2957 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1442 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1097 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0895 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0752 - accuracy: 0.9760


The `Model.evaluate` method checks the models performance, usually on a "Validation-set" or "Test-set"

In [78]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0744 - accuracy: 0.9775 - 1s/epoch - 3ms/step


[0.07436790317296982, 0.9775000214576721]

The image classifier is now trained to 98% accuracy on this dataset. To learn more, read the Tensorflow tutorials

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [79]:
probability_model = tf.keras.Sequential([
               model,
               tf.keras.layers.Softmax()                          
])

In [80]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4628214e-08, 1.2665654e-08, 7.3876599e-06, 5.7185092e-04,
        3.9738737e-12, 4.4664748e-07, 2.8508181e-14, 9.9941087e-01,
        4.5455945e-07, 8.9601945e-06],
       [4.0282924e-09, 2.6370413e-05, 9.9997163e-01, 1.5997933e-06,
        1.1256807e-14, 2.5024212e-07, 9.6364289e-08, 2.6169340e-16,
        1.4321797e-08, 1.9618106e-16],
       [1.8235268e-06, 9.9778110e-01, 3.3699672e-04, 3.4052911e-05,
        3.2062442e-05, 8.4346848e-06, 6.6973407e-05, 5.3826964e-04,
        1.1944546e-03, 5.7719903e-06],
       [9.9997985e-01, 2.9491617e-11, 2.2565944e-06, 1.3869678e-09,
        4.6535359e-07, 4.0422892e-06, 5.0180511e-06, 7.5689923e-06,
        9.1375157e-10, 8.2748147e-07],
       [7.3257695e-07, 8.5258717e-10, 7.5674961e-07, 1.7007447e-09,
        9.9839920e-01, 3.6622754e-07, 4.3202343e-07, 8.6951877e-05,
        9.3582592e-08, 1.5114337e-03]], dtype=float32)>

In [81]:
model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ -6.9941707 ,  -7.1382284 ,  -0.7695558 ,   3.5795112 ,
        -15.205137  ,  -3.5753531 , -20.142443  ,  11.045554  ,
         -3.5577931 ,  -0.57657504],
       [ -5.146657  ,   3.6399994 ,  14.183239  ,   0.8376309 ,
        -17.934534  ,  -1.0175697 ,  -1.9718623 , -21.69609   ,
         -3.8782153 , -21.984226  ],
       [ -7.1367097 ,   6.0758066 ,  -1.9174094 ,  -4.2095675 ,
         -4.2697973 ,  -5.60513   ,  -3.533187  ,  -1.449123  ,
         -0.65203774,  -5.984465  ],
       [ 10.220685  , -14.026209  ,  -2.7809486 , -10.17544   ,
         -4.3597627 ,  -2.1979945 ,  -1.9817642 ,  -1.5707457 ,
        -10.592756  ,  -3.7841742 ],
       [ -3.9384615 , -10.6945095 ,  -3.9059975 , -10.003964  ,
         10.186634  ,  -4.6317744 ,  -4.46655   ,   0.83808017,
         -5.9961853 ,   3.6935399 ]], dtype=float32)>